// Generated by scripts/sync-config.mjs from config.yaml — do not edit by hand.
export interface Product {
  id: string;
  name: string;
  /** Debian repo base URL; dists/<suite>/... is resolved under this. */
  repo: string;
  /** Preferred distro (optional) used when no suite is requested. */
  default?: string;
}
export const PRODUCTS: Product[] = [
  {
    "id": "pve",
    "name": "Proxmox VE",
    "repo": "http://download.proxmox.com/debian/pve",
    "default": "trixie"
  },
  {
    "id": "pve-ceph",
    "name": "Proxmox Ceph (Tentacle)",
    "repo": "http://download.proxmox.com/debian/ceph-tentacle",
    "default": "trixie"
  },
  {
    "id": "pbs",
    "name": "Proxmox Backup Server",
    "repo": "http://download.proxmox.com/debian/pbs",
    "default": "trixie"
  },
  {
    "id": "pbs-client",
    "name": "Proxmox Backup Server (Client)",
    "repo": "http://download.proxmox.com/debian/pbs-client",
    "default": "trixie"
  },
  {
    "id": "pdm",
    "name": "Proxmox Datacenter Manager",
    "repo": "http://download.proxmox.com/debian/pdm",
    "default": "trixie"
  },
  {
    "id": "pmg",
    "name": "Proxmox Mail Gateway",
    "repo": "http://download.proxmox.com/debian/pmg",
    "default": "trixie"
  }
];

export type CacheKey = "release" | "packages" | "changelog" | "listing";
/** Upstream-fetch cache TTLs in seconds, sourced from config.yaml. */
export const CACHE_SECONDS: Record<CacheKey, number> = {
  "release": 300,
  "packages": 900,
  "changelog": 3600,
  "listing": 900
};
