// Generates src/shared/config.ts from config.yaml. Run via `npm run sync`
// (wired into prebuild/predev/pretypecheck) whenever config.yaml changes.
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";

const src = readFileSync("config.yaml", "utf8");
const doc = parse(src);

const products = doc.products.map((p) => ({
  id: p.id,
  name: p.name,
  repo: p.repo,
  ...(p.default ? { default: p.default } : {}),
}));

const CACHE_DEFAULTS = { release: 300, packages: 900, changelog: 3600, listing: 900 };
const cache = {};
for (const key of Object.keys(CACHE_DEFAULTS)) {
  const value = Number(doc.cache?.[key]);
  cache[key] = Number.isFinite(value) && value > 0 ? value : CACHE_DEFAULTS[key];
}

const body = `// Generated by scripts/sync-config.mjs from config.yaml — do not edit by hand.
export interface Product {
  id: string;
  name: string;
  /** Debian repo base URL; dists/<suite>/... is resolved under this. */
  repo: string;
  /** Preferred distro (optional) used when no suite is requested. */
  default?: string;
}
export const PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};

export type CacheKey = "release" | "packages" | "changelog" | "listing";
/** Upstream-fetch cache TTLs in seconds, sourced from config.yaml. */
export const CACHE_SECONDS: Record<CacheKey, number> = ${JSON.stringify(cache, null, 2)};
`;

writeFileSync("src/shared/config.ts", body);
console.log(`config.yaml -> src/shared/config.ts (${products.length} products, ${Object.keys(cache).length} cache keys)`);