// Generates src/shared/config.ts from config.yaml. Run via `npm run sync`
// (wired into prebuild/predev/pretypecheck) whenever config.yaml changes.
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "yaml";

const src = readFileSync("config.yaml", "utf8");
const doc = parse(src);

const products = doc.products.map((p) => ({
  id: p.id,
  name: p.name,
  repo: p.repo,
  ...(p.default ? { default: p.default } : {}),
}));

const body = `// Generated by scripts/sync-config.mjs from config.yaml — do not edit by hand.
export interface Product {
  id: string;
  name: string;
  /** Debian repo base URL; dists/<suite>/... is resolved under this. */
  repo: string;
  /** Preferred distro (optional) used when no suite is requested. */
  default?: string;
}
export const PRODUCTS: Product[] = ${JSON.stringify(products, null, 2)};
`;

writeFileSync("src/shared/config.ts", body);
console.log(`config.yaml -> src/shared/config.ts (${products.length} products)`);